/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface App404 {
    }
    interface AppComponents {
    }
    interface AppContribution {
    }
    interface AppDesignSystem {
    }
    interface AppGettingStarted {
    }
    interface AppHome {
        "history": RouterHistory;
    }
    interface AppInstallation {
    }
    interface AppIntroduction {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppSupport {
    }
    interface AppWelcome {
    }
    interface AppWhy {
    }
    interface ComponentsButton {
    }
    interface CrossButton {
        "active": boolean;
        "circle": boolean;
        "color": string;
        "disabled": boolean;
        "fullWidth": boolean;
        "onBlur": ($event?) => void;
        "onClick": ($event?) => void;
        "onFocus": ($event?) => void;
        "outline": boolean;
        "pill": boolean;
        "selected": boolean;
        "size": string;
        "square": boolean;
        "type": string;
    }
}
declare global {
    interface HTMLApp404Element extends Components.App404, HTMLStencilElement {
    }
    var HTMLApp404Element: {
        prototype: HTMLApp404Element;
        new (): HTMLApp404Element;
    };
    interface HTMLAppComponentsElement extends Components.AppComponents, HTMLStencilElement {
    }
    var HTMLAppComponentsElement: {
        prototype: HTMLAppComponentsElement;
        new (): HTMLAppComponentsElement;
    };
    interface HTMLAppContributionElement extends Components.AppContribution, HTMLStencilElement {
    }
    var HTMLAppContributionElement: {
        prototype: HTMLAppContributionElement;
        new (): HTMLAppContributionElement;
    };
    interface HTMLAppDesignSystemElement extends Components.AppDesignSystem, HTMLStencilElement {
    }
    var HTMLAppDesignSystemElement: {
        prototype: HTMLAppDesignSystemElement;
        new (): HTMLAppDesignSystemElement;
    };
    interface HTMLAppGettingStartedElement extends Components.AppGettingStarted, HTMLStencilElement {
    }
    var HTMLAppGettingStartedElement: {
        prototype: HTMLAppGettingStartedElement;
        new (): HTMLAppGettingStartedElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppInstallationElement extends Components.AppInstallation, HTMLStencilElement {
    }
    var HTMLAppInstallationElement: {
        prototype: HTMLAppInstallationElement;
        new (): HTMLAppInstallationElement;
    };
    interface HTMLAppIntroductionElement extends Components.AppIntroduction, HTMLStencilElement {
    }
    var HTMLAppIntroductionElement: {
        prototype: HTMLAppIntroductionElement;
        new (): HTMLAppIntroductionElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppSupportElement extends Components.AppSupport, HTMLStencilElement {
    }
    var HTMLAppSupportElement: {
        prototype: HTMLAppSupportElement;
        new (): HTMLAppSupportElement;
    };
    interface HTMLAppWelcomeElement extends Components.AppWelcome, HTMLStencilElement {
    }
    var HTMLAppWelcomeElement: {
        prototype: HTMLAppWelcomeElement;
        new (): HTMLAppWelcomeElement;
    };
    interface HTMLAppWhyElement extends Components.AppWhy, HTMLStencilElement {
    }
    var HTMLAppWhyElement: {
        prototype: HTMLAppWhyElement;
        new (): HTMLAppWhyElement;
    };
    interface HTMLComponentsButtonElement extends Components.ComponentsButton, HTMLStencilElement {
    }
    var HTMLComponentsButtonElement: {
        prototype: HTMLComponentsButtonElement;
        new (): HTMLComponentsButtonElement;
    };
    interface HTMLCrossButtonElement extends Components.CrossButton, HTMLStencilElement {
    }
    var HTMLCrossButtonElement: {
        prototype: HTMLCrossButtonElement;
        new (): HTMLCrossButtonElement;
    };
    interface HTMLElementTagNameMap {
        "app-404": HTMLApp404Element;
        "app-components": HTMLAppComponentsElement;
        "app-contribution": HTMLAppContributionElement;
        "app-design-system": HTMLAppDesignSystemElement;
        "app-getting-started": HTMLAppGettingStartedElement;
        "app-home": HTMLAppHomeElement;
        "app-installation": HTMLAppInstallationElement;
        "app-introduction": HTMLAppIntroductionElement;
        "app-menu": HTMLAppMenuElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-support": HTMLAppSupportElement;
        "app-welcome": HTMLAppWelcomeElement;
        "app-why": HTMLAppWhyElement;
        "components-button": HTMLComponentsButtonElement;
        "cross-button": HTMLCrossButtonElement;
    }
}
declare namespace LocalJSX {
    interface App404 {
    }
    interface AppComponents {
    }
    interface AppContribution {
    }
    interface AppDesignSystem {
    }
    interface AppGettingStarted {
    }
    interface AppHome {
        "history"?: RouterHistory;
    }
    interface AppInstallation {
    }
    interface AppIntroduction {
    }
    interface AppMenu {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppSupport {
    }
    interface AppWelcome {
    }
    interface AppWhy {
    }
    interface ComponentsButton {
    }
    interface CrossButton {
        "active"?: boolean;
        "circle"?: boolean;
        "color"?: string;
        "disabled"?: boolean;
        "fullWidth"?: boolean;
        "onBlur"?: ($event?) => void;
        "onClick"?: ($event?) => void;
        "onFocus"?: ($event?) => void;
        "outline"?: boolean;
        "pill"?: boolean;
        "selected"?: boolean;
        "size"?: string;
        "square"?: boolean;
        "type"?: string;
    }
    interface IntrinsicElements {
        "app-404": App404;
        "app-components": AppComponents;
        "app-contribution": AppContribution;
        "app-design-system": AppDesignSystem;
        "app-getting-started": AppGettingStarted;
        "app-home": AppHome;
        "app-installation": AppInstallation;
        "app-introduction": AppIntroduction;
        "app-menu": AppMenu;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-support": AppSupport;
        "app-welcome": AppWelcome;
        "app-why": AppWhy;
        "components-button": ComponentsButton;
        "cross-button": CrossButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-404": LocalJSX.App404 & JSXBase.HTMLAttributes<HTMLApp404Element>;
            "app-components": LocalJSX.AppComponents & JSXBase.HTMLAttributes<HTMLAppComponentsElement>;
            "app-contribution": LocalJSX.AppContribution & JSXBase.HTMLAttributes<HTMLAppContributionElement>;
            "app-design-system": LocalJSX.AppDesignSystem & JSXBase.HTMLAttributes<HTMLAppDesignSystemElement>;
            "app-getting-started": LocalJSX.AppGettingStarted & JSXBase.HTMLAttributes<HTMLAppGettingStartedElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-installation": LocalJSX.AppInstallation & JSXBase.HTMLAttributes<HTMLAppInstallationElement>;
            "app-introduction": LocalJSX.AppIntroduction & JSXBase.HTMLAttributes<HTMLAppIntroductionElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-support": LocalJSX.AppSupport & JSXBase.HTMLAttributes<HTMLAppSupportElement>;
            "app-welcome": LocalJSX.AppWelcome & JSXBase.HTMLAttributes<HTMLAppWelcomeElement>;
            "app-why": LocalJSX.AppWhy & JSXBase.HTMLAttributes<HTMLAppWhyElement>;
            "components-button": LocalJSX.ComponentsButton & JSXBase.HTMLAttributes<HTMLComponentsButtonElement>;
            "cross-button": LocalJSX.CrossButton & JSXBase.HTMLAttributes<HTMLCrossButtonElement>;
        }
    }
}
