/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface CrossButton {
        "circle": boolean;
        "color": string;
        "disabled": boolean;
        "fullWidth": boolean;
        "pill": boolean;
        "selected": boolean;
        "size": string;
        "square": boolean;
        "type": string;
        "ui": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLCrossButtonElement extends Components.CrossButton, HTMLStencilElement {
    }
    var HTMLCrossButtonElement: {
        prototype: HTMLCrossButtonElement;
        new (): HTMLCrossButtonElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "cross-button": HTMLCrossButtonElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface CrossButton {
        "circle"?: boolean;
        "color"?: string;
        "disabled"?: boolean;
        "fullWidth"?: boolean;
        "pill"?: boolean;
        "selected"?: boolean;
        "size"?: string;
        "square"?: boolean;
        "type"?: string;
        "ui"?: string;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "cross-button": CrossButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "cross-button": LocalJSX.CrossButton & JSXBase.HTMLAttributes<HTMLCrossButtonElement>;
        }
    }
}
