name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    name: Jest Tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master

      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - name: Install all dependencies
        run: yarn install

      - name: Run Jest Tests
        # Use `yarn build` instead of `yarn test` because Stenciljs still have problems
        # https://github.com/ionic-team/stencil/issues/2942
        # https://github.com/ionic-team/stencil/pull/2980
        run: yarn build
